name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone GitHub Repo
        uses: amitgitz/github-repo-action@v3.1
        with:
          owner: amitgitz
          repository: https://github.com/amitgitz/GitOps.git
          access-token: ${{ secrets.ACCESS_TOKEN }}  # Use a GitHub Secret instead of a hardcoded token
          depth: full
          branch: main
