name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone GitHub Repo
        uses: whyakari/github-repo-action@v3.1
        with:
          owner: amitgitz
          repository: GitOps  # ✅ Corrected: Only repository name, not full URL
          access-token: ${{ secrets.ACCESS_TOKEN }}  # ✅ Securely stored in GitHub Secrets
          depth: 1
          branch: main
